GET http://localhost:3000/todos/?status=TO%20DO
###

GET http://localhost:3000/todos/?priority=HIGH
###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###

GET http://localhost:3000/todos/?search_q=Walking
###


PUT http://localhost:3000/todos/2/
Content-Type: application/json 

{ "status": "IN_PROGRESS" }
###

PUT http://localhost:3000/todos/1/
Content-Type: application/json 

{ "priority": "LOW" }
###

PUT http://localhost:3000/todos/1/
Content-Type: application/json 

{ "todo": "Some task" }
###

GET http://localhost:3000/todos/3/
###
